aplicaciones/ficha_personal/urls.py
from django.urls import path

from .views.empleados.views import EmpleadoListView, CrearEmpleado, ActualizarEmpleado, EliminarEmpleado
from .views.Departamento.views import DepartamentoListView, CrearDepartamento, ActualizarDepartamento, EliminarDepartamento
from .views.Cargo.views import CargoListView, CrearCargo, ActualizarCargo, EliminarCargo
from .views.ContactoEmergencia.views import ContactoEmergenciaListView, RegistroContactoEmergenciaListView, CrearContactoEmergencia, ActualizarContactoEmergencia, EliminarContactoEmergencia
from .views.InformacionAcademica.views import InfoAcademicaListView, RegistroInfoAcademicaListView, CrearInfoAcademica, ActualizarInfoAcademica, EliminarInfoAcademica
from .views.Capacitaciones.views import CapacitacionesListView, RegistroCapacitacionesListView, CrearCapacitaciones, ActualizarCapacitaciones, EliminarCapacitaciones
from .views.Sueldo.views import SueldoListView, RegistroSueldoListView, CrearSueldo, ActualizarSueldo, EliminarSueldo
from .views.fichaPersonal.views import FichaPersonalTemplateView

app_name = "ficha_Personal"  # nombre de la app
urlpatterns = [
    path('fichaPersonal', FichaPersonalTemplateView.as_view(), name="fichaPersonal"),
    path('empleado', EmpleadoListView.as_view(), name='empleado'),
    path('crearempleado/', CrearEmpleado.as_view(), name='crearempleado'),
    path('actualizarempleado/<int:pk>/', ActualizarEmpleado.as_view(), name='actualizarempleado'),
    path('eliminarempleado/<int:pk>/', EliminarEmpleado.as_view(), name='deleteempleado'),

    path('cargo', CargoListView.as_view(), name='cargo'),
    path('crearcargo/', CrearCargo.as_view(), name='crearcargo'),
    path('actualizarcargo/<int:pk>/', ActualizarCargo.as_view(), name='actualizarcargo'),
    path('eliminarcargo/<int:pk>/', EliminarCargo.as_view(), name='deletecargo'),

    path('departamento', DepartamentoListView.as_view(), name='departamento'),
    path('creardepartamento/', CrearDepartamento.as_view(), name='creardepartamento'),
    path('actualizardepartamento/<int:pk>/', ActualizarDepartamento.as_view(), name='actualizardepartamento'),
    path('eliminardepartamento/<int:pk>/', EliminarDepartamento.as_view(), name='deletedepartamento'),

    path('contactoEmergencia', ContactoEmergenciaListView.as_view(), name='contactoEmergencia'),
    path('registroContactoEmergencia/<int:pk>/', RegistroContactoEmergenciaListView.as_view(), name='registroContactoEmergencia'),
    path('crearContactoEmergencias/', CrearContactoEmergencia.as_view(), name='crearContactoEmergencias'),
    path('actualizaContactoEmergencia/<int:pk>/', ActualizarContactoEmergencia.as_view(), name='actualizarContactoEmergencia'),
    path('eliminarContactoEmergencia/<int:pk>/', EliminarContactoEmergencia.as_view(), name='deleteContactoEmergencia'),

    path('infoAcademica', InfoAcademicaListView.as_view(), name='infoAcademica'),
    path('registroInfoAcademica/<int:pk>/', RegistroInfoAcademicaListView.as_view(), name='registroInfoAcademica'),
    path('crearInfoAcademica/', CrearInfoAcademica.as_view(), name='crearInfoAcademica'),
    path('actualizarInfoAcademica/<int:pk>/', ActualizarInfoAcademica.as_view(),name='actualizarInfoAcademica'),
    path('eliminarInfoAcademica/<int:pk>/', EliminarInfoAcademica.as_view(), name='deleteInfoAcademica'),

    path('capacitaciones', CapacitacionesListView.as_view(), name='capacitaciones'),
    path('registroCapacitaciones/<int:pk>/', RegistroCapacitacionesListView.as_view(), name='registroCapacitaciones'),
    path('crearCapacitaciones/', CrearCapacitaciones.as_view(), name='crearCapacitaciones'),
    path('actualizarCapacitaciones/<int:pk>/', ActualizarCapacitaciones.as_view(), name='actualizarCapacitaciones'),
    path('eliminarCapacitaciones/<int:pk>/', EliminarCapacitaciones.as_view(), name='deleteCapacitaciones'),

    path('sueldo', SueldoListView.as_view(), name='sueldo'),
    path('registroSueldo/<int:pk>/', RegistroSueldoListView.as_view(), name='registroSueldo'),
    path('crearSueldo/', CrearSueldo.as_view(), name='crearSueldo'),
    path('actualizarSueldo/<int:pk>/', ActualizarSueldo.as_view(), name='actualizarSueldo'),
    path('eliminarSueldo/<int:pk>/', EliminarSueldo.as_view(), name='deleteSueldo'),
]

proyecto_administrativo/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from aplicaciones.core.views import InicioTemplateView
from proyecto_administrativo import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',InicioTemplateView.as_view(),name="inicio"),
    path('venta/', include('aplicaciones.ventas.urls')),
    path('fichaPersonal/', include('aplicaciones.ficha_personal.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplicaciones/ficha_personal/views/Capacitaciones/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, DeleteView, UpdateView
from aplicaciones.ficha_personal.forms import CapacitacionesForm
from aplicaciones.ficha_personal.models import Capacitaciones

class CapacitacionesListView(ListView):
    template_name = "Capacitaciones/listCapacitaciones.html"
    context_object_name = 'capacitacion'
    model = Capacitaciones
    paginate_by = 3
    #queryset = Cliente.objects.filter(estado=True)

    def get_queryset(self):
        query = self.request.GET.get("query")
        print(query)
        if query:
            return self.model.objects.filter(empleado__nombres=query)
        else:
            return self.model.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url_anterior'] = '/fichaPersonal/fichaPersonal'
        context['listar_url']= '/fichaPersonal/capacitaciones'
        context['crear_url'] = '/fichaPersonal/crearCapacitaciones/'
        context['titulo'] = 'LISTADO DE CAPACITACIONES'
        context['query'] = self.request.GET.get("query") or ""
        return context

class RegistroCapacitacionesListView(ListView):
    template_name = "Capacitaciones/registroCapacitaciones.html"
    context_object_name = 'capacitaciones'
    model = Capacitaciones
    paginate_by = 3
    #queryset = Cliente.objects.filter(estado=True)

    def get_queryset(self):
        print("mira", type(self.kwargs['pk']), self.kwargs['pk'])
        return self.model.objects.filter(empleado__id=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url_anterior'] = '/fichaPersonal/capacitaciones'
        context['listar_url']= '/fichaPersonal/registroCapacitaciones'
        context['crear_url'] = '/fichaPersonal/crearCapacitaciones/'
        context['titulo'] = 'REGISTRO DE CAPACITACIONES'
        context['query'] = self.request.GET.get("query") or ""
        return context

class CrearCapacitaciones(CreateView):
    model = Capacitaciones
    template_name = "Capacitaciones/form.html"
    success_url = reverse_lazy('ficha_Personal:capacitaciones')
    form_class = CapacitacionesForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = '/fichaPersonal/crearCapacitaciones/'
        context['titulo'] = 'CREAR CAPACITACIONES'
        context['url_anterior'] = '/fichaPersonal/capacitaciones'
        context['listar_url'] = '/fichaPersonal/capacitaciones'
        context['action'] = 'add'
        return context

class ActualizarCapacitaciones(UpdateView):
    model = Capacitaciones
    template_name = "Capacitaciones/form.html"
    success_url = reverse_lazy('ficha_Personal:capacitaciones')
    form_class = CapacitacionesForm
    #queryset = Cliente.objects.get(pk=request.GET.get("id"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'ACTUALIZAR DE CAPACITACIONES'
        context['url_anterior'] = '/fichaPersonal/capacitaciones'
        context['listar_url'] = '/fichaPersonal/capacitaciones'
        return context


class EliminarCapacitaciones(DeleteView):
    model = Capacitaciones
    template_name = "Capacitaciones/delete.html"
    success_url = reverse_lazy('ficha_Personal:capacitaciones')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'ELMINAR DE CAPACITACIONES'
        context['url_anterior'] = '/fichaPersonal/capacitaciones'
        context['listar_url'] = '/fichaPersonal/capacitaciones'
        return context

aplicaciones/ficha_personal/views/Cargo/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, DeleteView, UpdateView
from aplicaciones.ficha_personal.forms import CargoForm
from aplicaciones.ficha_personal.models import Cargo

class CargoListView(ListView):
    template_name = "Cargo/listCargos.html"
    context_object_name = 'cargo'
    model = Cargo
    paginate_by = 5
    #queryset = Cliente.objects.filter(estado=True)

    def get_queryset(self):
        query = self.request.GET.get("query")
        print(query)
        if query:
            return self.model.objects.filter(descripcion__icontains=query)
        else:
            return self.model.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url_anterior'] = '/fichaPersonal/fichaPersonal'
        context['listar_url']= '/fichaPersonal/cargo'
        context['crear_url'] = '/fichaPersonal/crearcargo/'
        context['titulo'] = 'LISTADO DE CARGOS'
        context['query'] = self.request.GET.get("query") or ""
        return context

class CrearCargo(CreateView):
    model = Cargo
    template_name = "Cargo/formCargo.html"
    success_url = reverse_lazy('ficha_Personal:cargo')
    form_class = CargoForm


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = '/fichaPersonal/crearcargo/'
        context['titulo'] = 'CREAR CARGO'
        context['url_anterior'] = '/fichaPersonal/cargo'
        context['listar_url'] = '/fichaPersonal/cargo'
        context['action'] = 'add'
        return context


class ActualizarCargo(UpdateView):
    model = Cargo
    template_name = "Cargo/formCargo.html"
    success_url = reverse_lazy('ficha_Personal:cargo')
    form_class = CargoForm
    #queryset = Cliente.objects.get(pk=request.GET.get("id"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'ACTUALIZAR CARGO'
        context['url_anterior'] = '/fichaPersonal/cargo'
        context['listar_url'] = '/fichaPersonal/cargo'
        return context


class EliminarCargo(DeleteView):
    model = Cargo
    template_name = "Cargo/eliminar_cargo.html"
    success_url = reverse_lazy('ficha_Personal:cargo')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'ELMINAR CARGO'
        context['url_anterior'] = '/fichaPersonal/cargo'
        context['listar_url'] = '/fichaPersonal/cargo'
        return context

aplicaciones/ficha_personal/views/ContactoEmergencia/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, DeleteView, UpdateView
from aplicaciones.ficha_personal.forms import ContactoEmergenciasForm
from aplicaciones.ficha_personal.models import ContactoEmergencias

class ContactoEmergenciaListView(ListView):
    template_name = "ContactoEmergencia/listContactoEmergencia.html"
    context_object_name = 'contactoEmergencia'
    model = ContactoEmergencias
    paginate_by = 3
    #queryset = Cliente.objects.filter(estado=True)

    def get_queryset(self):
        query = self.request.GET.get("query")
        print(query)
        if query:
            return self.model.objects.filter(empleado__nombres=query)
        else:
            return self.model.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url_anterior'] = '/fichaPersonal/fichaPersonal'
        context['listar_url']= '/fichaPersonal/contactoEmergencia'
        context['crear_url'] = '/fichaPersonal/crearContactoEmergencias/'
        context['titulo'] = 'LISTADO DE CONTACTO EMERGENCIAS'
        context['query'] = self.request.GET.get("query") or ""
        return context

class RegistroContactoEmergenciaListView(ListView):
    template_name = "ContactoEmergencia/registroContacto.html"
    model = ContactoEmergencias
    context_object_name = 'contactoEmergencias'
    paginate_by = 3
    # queryset = ContactoEmergencias.objects.filter(id=1)

    def get_queryset(self):
        # print("mira",type(self.kwargs['pk']),self.kwargs['pk'])
        return self.model.objects.filter(empleado__id=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url_anterior'] = '/fichaPersonal/contactoEmergencia'
        context['listar_url']= '/fichaPersonal/registroContactoEmergencia'
        context['crear_url'] = '/fichaPersonal/crearContactoEmergencias/'
        context['titulo'] = 'REGISTRO DE CONTACTO EMERGENCIAS'
        context['query'] = self.request.GET.get("query") or ""
        return context

class CrearContactoEmergencia(CreateView):
    model = ContactoEmergencias
    template_name = "ContactoEmergencia/form.html"
    success_url = reverse_lazy('ficha_Personal:contactoEmergencia')
    form_class = ContactoEmergenciasForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = '/fichaPersonal/crearContactoEmergencias/'
        context['titulo'] = 'CREAR CONTACTO EMERGENCIA'
        context['url_anterior'] = '/fichaPersonal/contactoEmergencia'
        context['listar_url'] = '/fichaPersonal/contactoEmergencia'
        context['action'] = 'add'
        return context

class ActualizarContactoEmergencia(UpdateView):
    model = ContactoEmergencias
    template_name = "ContactoEmergencia/form.html"
    # success_url = reverse_lazy('ficha_Personal:registroContactoEmergencia')
    success_url = reverse_lazy('ficha_Personal:contactoEmergencia')
    form_class = ContactoEmergenciasForm
    #queryset = Cliente.objects.get(pk=request.GET.get("id"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'ACTUALIZAR DE CONTACTO EMERGENCIA'
        context['url_anterior'] = '/fichaPersonal/contactoEmergencia'
        context['listar_url'] = '/fichaPersonal/contactoEmergencia'
        return context


class EliminarContactoEmergencia(DeleteView):
    model = ContactoEmergencias
    template_name = "ContactoEmergencia/delete.html"
    success_url = reverse_lazy('ficha_Personal:contactoEmergencia')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'ELMINAR DE CONTACTO EMERGENCIA'
        context['url_anterior'] = '/fichaPersonal/contactoEmergencia'
        context['listar_url'] = '/fichaPersonal/contactoEmergencia'
        return context

aplicaciones/ficha_personal/views/DatosMedicos/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, DeleteView, UpdateView
from aplicaciones.ficha_personal.forms import DatosMedicosForm
from aplicaciones.ficha_personal.models import DatosMedicos

aplicaciones/ficha_personal/views/fichaPersonal/views.py
from django.views.generic.base import TemplateView

class FichaPersonalTemplateView(TemplateView):
    template_name = 'fichaPersonal.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = "fichaPersonal"
        context['url_anterior'] = "/"
        return context

aplicaciones/ficha_personal/templates/Empleados/Prueba.html
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<div class="container">
  <form>
   <div class="form-group">
    <p>
      <label>Entre su Nombre:</label> <br>
      <input id="nombre" class="form-control" type="text" placeholder="Nombre..."><br>
    </p>
    <p>
      <label>Entre su Apellido:</label> <br>
      <input id="apellido" class="form-control" type="text" placeholder="Apellido..."><br>
    </p>
    <p>
      <label>Entre su C&eacute;dula:</label> <br>
      <input id="cedula" class="form-control" type="text" placeholder="Cedúla"> <br>
    </p>
    <button id="adicionar" class="btn btn-success" type="button">Adicionar a la tabla</button>
  </div>
</form>

<p>Elementos en la Tabla:
  <div id="adicionados"></div>
</p>
<table  id="mytable" class="table table-bordered table-hover ">
  <tr>
    <th>Nobmre</th>
    <th>Apellidos</th>
    <th>C&eacute;dula</th>
    <th>Eliminar</th>

  </tr>
</table>

</div>

aplicaciones/ficha_personal/templates/Empleados/delete.html
{% extends 'formulario.html' %}
{% load static %}


{% block controls %}
    {% csrf_token %}
    <p>Estas seguro de eliminar "{{ object }}"?</p>
{% endblock %}

aplicaciones/ficha_personal/templates/Empleados/form.html
{% extends 'formulario.html' %}
{% load static %}

{% block js %}
{#    <script src="{% static 'cliente/js/form.js' %}"></script>#}
{% endblock %}

{% block controls %}
    {% csrf_token %}
    {% if form.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong>Error al Grabar</strong> {{ form.errors }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

    {% endif %}
    <input type="hidden" name="action" value="{{ action }}">

    <h4 class="fw-bold fst-italic text-secondary text-center">DATOS PERSONALES</h4>
    <hr class="bg-success border-5 border-top border-success">
        <div class="form-group">
            <label class="fw-bold" >Nombre:</label>
            {{ form.nombres }}
        </div>
        <div class="form-group">
            <label class="fw-bold" >Cedula:</label>
            {{ form.cedula }}
        </div>
        <div class="form-group">
            <label class="fw-bold" >Fecha Nacimiento:</label>
            {{ form.fecha_nacimiento }}
        </div>
        <div class="form-group">
            <label class="fw-bold" >Género:</label>
            {{ form.genero }}
        </div>
        <div class="form-group">
            <label class="fw-bold" >País:</label>
            {{ form.pais }}
        </div>
        <div class="form-group">
            <label class="fw-bold" >Provincia:</label>
            {{ form.provincia }}
        </div>
        <div class="form-group">
            <label class="fw-bold" >Ciudad:</label>
            {{ form.ciudad }}
        </div>
        <div class="form-group">
            <label class="fw-bold" >Estado Civil:</label>
            {{ form.estado_civil }}
        </div>
        <div class="form-group">
            <label class="fw-bold" >Email:</label>
            {{ form.email }}
        </div>
        <div class="form-group">
            <label class="fw-bold" >Dirección:</label>
            {{ form.direccion }}
        </div>
        <div class="form-group">
            <label class="fw-bold" >Teléfono:</label>
            {{ form.telefonos }}
        </div>
        <div class="form-group">
            <label class="fw-bold" >Fecha IESS:</label>
            {{ form.fecha_IESS }}
        </div>
        <div class="form-group">
            <label class="fw-bold" >Tipo Contrato:</label>
            {{ form.tipo_Contrato }}
        </div>
        <div class="form-group">
            <label class="fw-bold" >Fecha Ingreso:</label>
            {{ form.fecha_Ingreso }}
        </div>
        <div class="form-group">
            <label class="fw-bold" >Foto:</label>
            {{ form.foto }}
        </div>
        <div class="form-group">
            <label class="fw-bold" >Cargo:</label>
            {{ form.cargo }}
        </div>
        <div class="form-group">
            <label class="fw-bold" >Departamento:</label>
            {{ form.departamento }}
        </div>
        <div class="form-group">
            <label class="fw-bold" >Estado</label>
            {{ form.estado }}
        </div>

    <hr class="bg-success border-5 border-top border-success">
    <h4 class="fw-bold fst-italic text-secondary text-center">SUELDO</h4>
    <hr class="bg-success border-5 border-top border-success">
        <table class="table table-info table-striped table-bordered border-dark text-center">
            <thead>
                <tr>
                  <th scope="col" style="width: 5%;">#</th>
                  <th scope="col" style="width: 10%;">Fecha</th>
                  <th scope="col" style="width: 10%;">Sueldo</th>
                  <th scope="col" style="width: 10%;">Estado</th>
                  <th scope="col" style="width: 10%;">Opciones</th>
                </tr>
              </thead>
               <tbody id="tablaSue">

               </tbody>

            {% for sue in sueldos %}
                <tbody>
                    <tr class="align-middle table-info table-bordered border-dark text-center">
                        <td>{{ forloop.counter}}</td>
                        <td>{{ sue.fecha }}</td>
                        <td>{{ sue.sueldo }}</td>
                        <td>{% if sue.estado %}
                                ✅ Activo
                            {% else %}
                                🚫 Anulada
                            {% endif %}
                        <td class="acciones">
                            <a href="{% url 'ficha_Personal:deleteSueldo' sue.id %}">❌</a>
                        </td>
                    </tr>
                </tbody>
            {% endfor %}
        </table>
        <div>
            <a class="btn btn-outline-info" href="{% url 'ficha_Personal:añadirSueldo' %}"><b>➕ Agregar</b></a>
        </div>
    <hr class="bg-success border-5 border-top border-success">
    <h4 class="fw-bold fst-italic text-secondary text-center">CONTACTO DE EMERGENCIAS</h4>
    <hr class="bg-success border-5 border-top border-success">
        <table class="table table-info table-striped table-bordered border-dark col-md-3 text-center">
            <thead>
                <tr class="text-center">
                    <th scope="col" style="width: 5px;">#</th>
                    <th scope="col" style="width: 20px;">Nombre</th>
                    <th scope="col" style="width: 10%;">Cèdula</th>
                    <th scope="col" style="width: 10%;">Teléfono</th>
                    <th scope="col" style="width: 10%;">Parentesco</th>
                    <th scope="col" style="width: 20%;">Dirección</th>
                    <th scope="col" style="width: 10%;">Opciones</th>
                </tr>
            </thead>

            {% for contaEmer in contactoEmergencias %}
                <tbody>
                <tr class="align-middle table-info table-bordered border-dark text-center">
                    <td>{{forloop.counter}}</td>
                    <td>{{ contaEmer.nombre }}</td>
                    <td>{{ contaEmer.cedula }}</td>
                    <td>{{ contaEmer.telefonos }}</td>
                    <td>{{ contaEmer.parentesco }}</td>
                    <td>{{ contaEmer.direccion }}</td>
                    <td class="acciones">
                        <a href="{% url 'ficha_Personal:deleteContactoEmergencia' contaEmer.id %}">❌</a>
                    </td>
                </tr>
                </tbody>
            {% endfor %}
        </table>
        <div>
            <a class="btn btn-outline-info" href="{% url 'ficha_Personal:crearContactoEmergencias' %}"><b>➕ Agregar</b></a>
        </div>
    <hr class="bg-success border-5 border-top border-success">
    <h4 class="fw-bold fst-italic text-secondary text-center">INFORMACIÓN ACADÉMICA</h4>
    <hr class="bg-success border-5 border-top border-success">
        <table class="table table-info table-striped table-bordered border-dark text-center">
            <thead>
                <tr>
                  <th scope="col" style="width: 5%;">#</th>
                  <th scope="col" style="width: 10%;">Fecha Inicio</th>
                  <th scope="col" style="width: 10%;">Fecha Fin</th>
                  <th scope="col" style="width: 10%;">Institución</th>
                  <th scope="col" style="width: 10%;">Título</th>
                  <th scope="col" style="width: 10%;">Opciones</th>
                </tr>
              </thead>

            {% for infoAcade in infoAcademicas %}
                <tbody>
                    <tr class="align-middle table-info table-bordered border-dark text-center">
                        <td>{{forloop.counter}}</td>
                        <td>{{ infoAcade.fecha_Inicio }}</td>
                        <td>{{ infoAcade.fecha_Fin }}</td>
                        <td>{{ infoAcade.institucion }}</td>
                        <td>{{ infoAcade.titulo }}</td>
                        <td class="acciones">
                            <a href="{% url 'ficha_Personal:deleteInfoAcademica' infoAcade.id %}">❌</a>
                        </td>
                    </tr>
                </tbody>
            {% endfor %}
        </table>
        <div>
            <a class="btn btn-outline-info" href="{% url 'ficha_Personal:crearInfoAcademica' %}"><b>➕ Agregar</b></a>
        </div>
    <hr class="bg-success border-5 border-top border-success">
    <h4 class="fw-bold fst-italic text-secondary text-center">CAPACITACIONES</h4>
    <hr class="bg-success border-5 border-top border-success">
        <table class="table table-info table-striped table-bordered border-dark">
            <thead>
                <tr class="text-center">
                    <th scope="col" style="width: 5%;">#</th>
                    <th scope="col" style="width: 15%;">Certificado</th>
                    <th scope="col" style="width: 10%;">Fecha Inicio</th>
                    <th scope="col" style="width: 10%;">Fecha Fin</th>
                    <th scope="col" style="width: 10%;">Duraciono</th>
                    <th scope="col" style="width: 10%;">Opciones</th>
                </tr>
            </thead>

            {% for cap in capacitaciones %}
                <tbody>
                    <tr class="align-middle table-warning">
                        <td>{{forloop.counter}}</td>
                        <td>{{ cap.certificado }}</td>
                        <td>{{ cap.fecha_Inicio }}</td>
                        <td>{{ cap.fecha_Fin }}</td>
                        <td>{{ cap.duracion }}</td>
                        <td class="acciones">
                            <a href="{% url 'ficha_Personal:deleteCapacitaciones' cap.id %}">❌</a>
                        </td>
                    </tr>
                </tbody>
            {% endfor %}
        </table>
        <div>
            <a class="btn btn-outline-info" href="{% url 'ficha_Personal:crearCapacitaciones' %}"><b>➕ Agregar</b></a>
        </div>

    <output id="idImgContenedor" style="width: 200px !important;"></output>
{% endblock %}