aplicaciones/ficha_personal/urls.py
from django.urls import path

from .views.empleados.views import EmpleadoListView, CrearEmpleado, ActualizarEmpleado, EliminarEmpleado
from .views.Departamento.views import DepartamentoListView, CrearDepartamento, ActualizarDepartamento, EliminarDepartamento
from .views.Cargo.views import CargoListView, CrearCargo, ActualizarCargo, EliminarCargo
from .views.ContactoEmergencia.views import ContactoEmergenciaListView, RegistroContactoEmergenciaListView, CrearContactoEmergencia, ActualizarContactoEmergencia, EliminarContactoEmergencia
from .views.InformacionAcademica.views import InfoAcademicaListView, RegistroInfoAcademicaListView, CrearInfoAcademica, ActualizarInfoAcademica, EliminarInfoAcademica
from .views.Capacitaciones.views import CapacitacionesListView, RegistroCapacitacionesListView, CrearCapacitaciones, ActualizarCapacitaciones, EliminarCapacitaciones
from .views.Sueldo.views import SueldoListView, RegistroSueldoListView, CrearSueldo, ActualizarSueldo, EliminarSueldo
from .views.fichaPersonal.views import FichaPersonalTemplateView

app_name = "ficha_Personal"  # nombre de la app
urlpatterns = [
    path('fichaPersonal', FichaPersonalTemplateView.as_view(), name="fichaPersonal"),
    path('empleado', EmpleadoListView.as_view(), name='empleado'),
    path('crearempleado/', CrearEmpleado.as_view(), name='crearempleado'),
    path('actualizarempleado/<int:pk>/', ActualizarEmpleado.as_view(), name='actualizarempleado'),
    path('eliminarempleado/<int:pk>/', EliminarEmpleado.as_view(), name='deleteempleado'),

    path('cargo', CargoListView.as_view(), name='cargo'),
    path('crearcargo/', CrearCargo.as_view(), name='crearcargo'),
    path('actualizarcargo/<int:pk>/', ActualizarCargo.as_view(), name='actualizarcargo'),
    path('eliminarcargo/<int:pk>/', EliminarCargo.as_view(), name='deletecargo'),

    path('departamento', DepartamentoListView.as_view(), name='departamento'),
    path('creardepartamento/', CrearDepartamento.as_view(), name='creardepartamento'),
    path('actualizardepartamento/<int:pk>/', ActualizarDepartamento.as_view(), name='actualizardepartamento'),
    path('eliminardepartamento/<int:pk>/', EliminarDepartamento.as_view(), name='deletedepartamento'),

    path('contactoEmergencia', ContactoEmergenciaListView.as_view(), name='contactoEmergencia'),
    path('registroContactoEmergencia/<int:pk>/', RegistroContactoEmergenciaListView.as_view(), name='registroContactoEmergencia'),
    path('crearContactoEmergencias/', CrearContactoEmergencia.as_view(), name='crearContactoEmergencias'),
    path('actualizaContactoEmergencia/<int:pk>/', ActualizarContactoEmergencia.as_view(), name='actualizarContactoEmergencia'),
    path('eliminarContactoEmergencia/<int:pk>/', EliminarContactoEmergencia.as_view(), name='deleteContactoEmergencia'),

    path('infoAcademica', InfoAcademicaListView.as_view(), name='infoAcademica'),
    path('registroInfoAcademica/<int:pk>/', RegistroInfoAcademicaListView.as_view(), name='registroInfoAcademica'),
    path('crearInfoAcademica/', CrearInfoAcademica.as_view(), name='crearInfoAcademica'),
    path('actualizarInfoAcademica/<int:pk>/', ActualizarInfoAcademica.as_view(),name='actualizarInfoAcademica'),
    path('eliminarInfoAcademica/<int:pk>/', EliminarInfoAcademica.as_view(), name='deleteInfoAcademica'),

    path('capacitaciones', CapacitacionesListView.as_view(), name='capacitaciones'),
    path('registroCapacitaciones/<int:pk>/', RegistroCapacitacionesListView.as_view(), name='registroCapacitaciones'),
    path('crearCapacitaciones/', CrearCapacitaciones.as_view(), name='crearCapacitaciones'),
    path('actualizarCapacitaciones/<int:pk>/', ActualizarCapacitaciones.as_view(), name='actualizarCapacitaciones'),
    path('eliminarCapacitaciones/<int:pk>/', EliminarCapacitaciones.as_view(), name='deleteCapacitaciones'),

    path('sueldo', SueldoListView.as_view(), name='sueldo'),
    path('registroSueldo/<int:pk>/', RegistroSueldoListView.as_view(), name='registroSueldo'),
    path('crearSueldo/', CrearSueldo.as_view(), name='crearSueldo'),
    path('actualizarSueldo/<int:pk>/', ActualizarSueldo.as_view(), name='actualizarSueldo'),
    path('eliminarSueldo/<int:pk>/', EliminarSueldo.as_view(), name='deleteSueldo'),
]

proyecto_administrativo/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from aplicaciones.core.views import InicioTemplateView
from proyecto_administrativo import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',InicioTemplateView.as_view(),name="inicio"),
    path('venta/', include('aplicaciones.ventas.urls')),
    path('fichaPersonal/', include('aplicaciones.ficha_personal.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplicaciones/ficha_personal/views/Capacitaciones/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, DeleteView, UpdateView
from aplicaciones.ficha_personal.forms import CapacitacionesForm
from aplicaciones.ficha_personal.models import Capacitaciones

class CapacitacionesListView(ListView):
    template_name = "Capacitaciones/listCapacitaciones.html"
    context_object_name = 'capacitacion'
    model = Capacitaciones
    paginate_by = 3
    #queryset = Cliente.objects.filter(estado=True)

    def get_queryset(self):
        query = self.request.GET.get("query")
        print(query)
        if query:
            return self.model.objects.filter(empleado__nombres=query)
        else:
            return self.model.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url_anterior'] = '/fichaPersonal/fichaPersonal'
        context['listar_url']= '/fichaPersonal/capacitaciones'
        context['crear_url'] = '/fichaPersonal/crearCapacitaciones/'
        context['titulo'] = 'LISTADO DE CAPACITACIONES'
        context['query'] = self.request.GET.get("query") or ""
        return context

class RegistroCapacitacionesListView(ListView):
    template_name = "Capacitaciones/registroCapacitaciones.html"
    context_object_name = 'capacitaciones'
    model = Capacitaciones
    paginate_by = 3
    #queryset = Cliente.objects.filter(estado=True)

    def get_queryset(self):
        print("mira", type(self.kwargs['pk']), self.kwargs['pk'])
        return self.model.objects.filter(empleado__id=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url_anterior'] = '/fichaPersonal/capacitaciones'
        context['listar_url']= '/fichaPersonal/registroCapacitaciones'
        context['crear_url'] = '/fichaPersonal/crearCapacitaciones/'
        context['titulo'] = 'REGISTRO DE CAPACITACIONES'
        context['query'] = self.request.GET.get("query") or ""
        return context

class CrearCapacitaciones(CreateView):
    model = Capacitaciones
    template_name = "Capacitaciones/form.html"
    success_url = reverse_lazy('ficha_Personal:capacitaciones')
    form_class = CapacitacionesForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = '/fichaPersonal/crearCapacitaciones/'
        context['titulo'] = 'CREAR CAPACITACIONES'
        context['url_anterior'] = '/fichaPersonal/capacitaciones'
        context['listar_url'] = '/fichaPersonal/capacitaciones'
        context['action'] = 'add'
        return context

class ActualizarCapacitaciones(UpdateView):
    model = Capacitaciones
    template_name = "Capacitaciones/form.html"
    success_url = reverse_lazy('ficha_Personal:capacitaciones')
    form_class = CapacitacionesForm
    #queryset = Cliente.objects.get(pk=request.GET.get("id"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'ACTUALIZAR DE CAPACITACIONES'
        context['url_anterior'] = '/fichaPersonal/capacitaciones'
        context['listar_url'] = '/fichaPersonal/capacitaciones'
        return context


class EliminarCapacitaciones(DeleteView):
    model = Capacitaciones
    template_name = "Capacitaciones/delete.html"
    success_url = reverse_lazy('ficha_Personal:capacitaciones')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'ELMINAR DE CAPACITACIONES'
        context['url_anterior'] = '/fichaPersonal/capacitaciones'
        context['listar_url'] = '/fichaPersonal/capacitaciones'
        return context

aplicaciones/ficha_personal/views/Cargo/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, DeleteView, UpdateView
from aplicaciones.ficha_personal.forms import CargoForm
from aplicaciones.ficha_personal.models import Cargo

class CargoListView(ListView):
    template_name = "Cargo/listCargos.html"
    context_object_name = 'cargo'
    model = Cargo
    paginate_by = 5
    #queryset = Cliente.objects.filter(estado=True)

    def get_queryset(self):
        query = self.request.GET.get("query")
        print(query)
        if query:
            return self.model.objects.filter(descripcion__icontains=query)
        else:
            return self.model.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url_anterior'] = '/fichaPersonal/fichaPersonal'
        context['listar_url']= '/fichaPersonal/cargo'
        context['crear_url'] = '/fichaPersonal/crearcargo/'
        context['titulo'] = 'LISTADO DE CARGOS'
        context['query'] = self.request.GET.get("query") or ""
        return context

class CrearCargo(CreateView):
    model = Cargo
    template_name = "Cargo/formCargo.html"
    success_url = reverse_lazy('ficha_Personal:cargo')
    form_class = CargoForm


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = '/fichaPersonal/crearcargo/'
        context['titulo'] = 'CREAR CARGO'
        context['url_anterior'] = '/fichaPersonal/cargo'
        context['listar_url'] = '/fichaPersonal/cargo'
        context['action'] = 'add'
        return context


class ActualizarCargo(UpdateView):
    model = Cargo
    template_name = "Cargo/formCargo.html"
    success_url = reverse_lazy('ficha_Personal:cargo')
    form_class = CargoForm
    #queryset = Cliente.objects.get(pk=request.GET.get("id"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'ACTUALIZAR CARGO'
        context['url_anterior'] = '/fichaPersonal/cargo'
        context['listar_url'] = '/fichaPersonal/cargo'
        return context


class EliminarCargo(DeleteView):
    model = Cargo
    template_name = "Cargo/eliminar_cargo.html"
    success_url = reverse_lazy('ficha_Personal:cargo')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'ELMINAR CARGO'
        context['url_anterior'] = '/fichaPersonal/cargo'
        context['listar_url'] = '/fichaPersonal/cargo'
        return context

aplicaciones/ficha_personal/views/ContactoEmergencia/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, DeleteView, UpdateView
from aplicaciones.ficha_personal.forms import ContactoEmergenciasForm
from aplicaciones.ficha_personal.models import ContactoEmergencias

class ContactoEmergenciaListView(ListView):
    template_name = "ContactoEmergencia/listContactoEmergencia.html"
    context_object_name = 'contactoEmergencia'
    model = ContactoEmergencias
    paginate_by = 3
    #queryset = Cliente.objects.filter(estado=True)

    def get_queryset(self):
        query = self.request.GET.get("query")
        print(query)
        if query:
            return self.model.objects.filter(empleado__nombres=query)
        else:
            return self.model.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url_anterior'] = '/fichaPersonal/fichaPersonal'
        context['listar_url']= '/fichaPersonal/contactoEmergencia'
        context['crear_url'] = '/fichaPersonal/crearContactoEmergencias/'
        context['titulo'] = 'LISTADO DE CONTACTO EMERGENCIAS'
        context['query'] = self.request.GET.get("query") or ""
        return context

class RegistroContactoEmergenciaListView(ListView):
    template_name = "ContactoEmergencia/registroContacto.html"
    model = ContactoEmergencias
    context_object_name = 'contactoEmergencias'
    paginate_by = 3
    # queryset = ContactoEmergencias.objects.filter(id=1)

    def get_queryset(self):
        # print("mira",type(self.kwargs['pk']),self.kwargs['pk'])
        return self.model.objects.filter(empleado__id=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url_anterior'] = '/fichaPersonal/contactoEmergencia'
        context['listar_url']= '/fichaPersonal/registroContactoEmergencia'
        context['crear_url'] = '/fichaPersonal/crearContactoEmergencias/'
        context['titulo'] = 'REGISTRO DE CONTACTO EMERGENCIAS'
        context['query'] = self.request.GET.get("query") or ""
        return context

class CrearContactoEmergencia(CreateView):
    model = ContactoEmergencias
    template_name = "ContactoEmergencia/form.html"
    success_url = reverse_lazy('ficha_Personal:contactoEmergencia')
    form_class = ContactoEmergenciasForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = '/fichaPersonal/crearContactoEmergencias/'
        context['titulo'] = 'CREAR CONTACTO EMERGENCIA'
        context['url_anterior'] = '/fichaPersonal/contactoEmergencia'
        context['listar_url'] = '/fichaPersonal/contactoEmergencia'
        context['action'] = 'add'
        return context

class ActualizarContactoEmergencia(UpdateView):
    model = ContactoEmergencias
    template_name = "ContactoEmergencia/form.html"
    # success_url = reverse_lazy('ficha_Personal:registroContactoEmergencia')
    success_url = reverse_lazy('ficha_Personal:contactoEmergencia')
    form_class = ContactoEmergenciasForm
    #queryset = Cliente.objects.get(pk=request.GET.get("id"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'ACTUALIZAR DE CONTACTO EMERGENCIA'
        context['url_anterior'] = '/fichaPersonal/contactoEmergencia'
        context['listar_url'] = '/fichaPersonal/contactoEmergencia'
        return context


class EliminarContactoEmergencia(DeleteView):
    model = ContactoEmergencias
    template_name = "ContactoEmergencia/delete.html"
    success_url = reverse_lazy('ficha_Personal:contactoEmergencia')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'ELMINAR DE CONTACTO EMERGENCIA'
        context['url_anterior'] = '/fichaPersonal/contactoEmergencia'
        context['listar_url'] = '/fichaPersonal/contactoEmergencia'
        return context

aplicaciones/ficha_personal/views/DatosMedicos/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, DeleteView, UpdateView
from aplicaciones.ficha_personal.forms import DatosMedicosForm
from aplicaciones.ficha_personal.models import DatosMedicos

aplicaciones/ficha_personal/views/fichaPersonal/views.py
from django.views.generic.base import TemplateView

class FichaPersonalTemplateView(TemplateView):
    template_name = 'fichaPersonal.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = "fichaPersonal"
        context['url_anterior'] = "/"
        return context

aplicaciones/ficha_personal/templates/Sueldo/crearSueldo.html
{% extends 'formulario.html' %}
{% load static %}
{
{% block js %}
{#    <script src="{% static 'cliente/js/form.js' %}"></script>#}
{% endblock %}

{% block controls %}
    {% csrf_token %}
    {% if form.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong>Error al Grabar</strong> {{ form.errors }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

    {% endif %}

    <input type="hidden" name="action" value="{{ action }}">
    {{ form.as_p }}
    <output id="idImgContenedor" style="width: 200px !important;"></output>
{% endblock %}

aplicaciones/ficha_personal/templates/Sueldo/delete.html
{% extends 'formulario.html' %}
{% load static %}


{% block controls %}
    {% csrf_token %}
    <p>Estas seguro de eliminar "{{ object }}"?</p>
{% endblock %}

aplicaciones/ficha_personal/templates/Sueldo/eliminarSueldo.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Formulario Sueldo</title>
    {% load static %}
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/form.css' %}">

</head>
<body >

    <div style="background: lightcoral; text-align: center; padding:10px;">
        <h2> ELIMINACIÓN DE SUELDO</h2>
    </div>
    <br>
  <section class="form-container ">
      <h2 class="fs-2"; style="text-align: center;">¿Desea Eliminar el Sueldo?</h2>
        <div class="fw-semibold">
            <a class="btn "; style="display:block;background:red;border-radius:5px;padding:5px;color:white;cursor:pointer;text-align: center"
               href="{% url 'sueldo' %}">ELIMINAR</a>
        </div>
    <br>
        <div class="fw-semibold">
            <a class="btn "; style="display:block;background:green;border-radius:5px;padding:5px;color:white;cursor:pointer;text-align: center"
            href="{% url 'sueldo' %}">CANCELAR 🚫</a>
        </div>

  </section>

</body>
</html>

aplicaciones/ficha_personal/templates/Sueldo/form.html
{% extends 'formulario.html' %}
{% load static %}
{
{% block js %}
{#    <script src="{% static 'cliente/js/form.js' %}"></script>#}
{% endblock %}

{% block controls %}
    {% csrf_token %}
    {% if form.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong>Error al Grabar</strong> {{ form.errors }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

    {% endif %}

    <input type="hidden" name="action" value="{{ action }}">
    {{ form.as_p }}
    <output id="idImgContenedor" style="width: 200px !important;"></output>
{% endblock %}

aplicaciones/ficha_personal/templates/Sueldo/formSueldo.html
{% extends 'FichaPersonal/sueldo/formularioSueldo.html' %}
{% load static %}

{% block controls %}
    <h4 class="fw-bold fst-italic text-secondary text-center">SUELDOS</h4>
    <hr class="bg-success border-4 border-top border-success">
        <div class="col-md-6">
            <label class="form-label fw-bold">Id Sueldo:</label>
            <input type="text" class="form-control" placeholder="Ingrese ID de sueldo">
        </div>
        <div class="col-md-6">
            <label class="form-label fw-bold">Fecha:</label>
            <input type="date" class="form-control" placeholder="Ingrese fecha de pago de sueldo">
        </div>
        <div class="col-12">
            <label for="inputState" class="form-label fw-bold">Codigo Empleado:</label>
            <select id="inputState" class="form-select" style="width: 650px;">
                <option selected>-------</option>
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
            </select>
        </div>
        <div class="col-12">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck">
                <label class="form-check-label" for="gridCheck">
                    Estado
                </label>
            </div>
        </div>

{% endblock %}

aplicaciones/ficha_personal/templates/Sueldo/formularioSueldo.html
{% extends 'base.html' %}
{% load static %}
run
{% block main %}
    <form method="post" action="{% url 'sueldo' %}" enctype="multipart/form-data">
        <div class="card card-primary">
            <div class="card-header bg-success">
                <h5 class="card-title text-center text-white">
                   {{ titulo }}
                </h5>
            </div>
            <div class="card-body row g-3">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% block controls %}

                {% endblock %}
            </div>
            <div class="card-footer ">
                <button type="submit" class="btn btn-primary btn-flat">
                    <a onclick="alert('REGISTRO NUEVO GUARDADO CON ÉXITO');"href="{% url 'sueldo' %}" class="btn btn-primary btn-flat btnTest">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-save2" viewBox="0 0 16 16">
                            <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v4.5h2a.5.5 0 0 1 .354.854l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5A.5.5 0 0 1 5.5 6.5h2V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                        </svg> Guardar registro
                    </a>
                </button>
                <a href="{{ listar_url }}" class="btn btn-danger btn-flat">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-octagon" viewBox="0 0 16 16">
                      <path d="M4.54.146A.5.5 0 0 1 4.893 0h6.214a.5.5 0 0 1 .353.146l4.394 4.394a.5.5 0 0 1 .146.353v6.214a.5.5 0 0 1-.146.353l-4.394 4.394a.5.5 0 0 1-.353.146H4.893a.5.5 0 0 1-.353-.146L.146 11.46A.5.5 0 0 1 0 11.107V4.893a.5.5 0 0 1 .146-.353L4.54.146zM5.1 1 1 5.1v5.8L5.1 15h5.8l4.1-4.1V5.1L10.9 1H5.1z"/>
                      <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                    </svg> Cancelar
                </a>
            </div>
        </div>
    </form>

{% endblock %}

aplicaciones/ficha_personal/templates/Sueldo/listSueldo.html
{% extends 'consulta.html' %}
{% load static %}

{% block js %}
{#    <script src="{% static 'cliente/js/list.js' %}"></script>#}
{% endblock %}

{% block search %}
    <form action="{% url 'ficha_Personal:sueldo' %}" method="GET">
      <div class="input-group mb-3">
        <input type="text" name="query" value="{{ query }}" class="form-control" placeholder="Buscar... por nombre" id="idInputSearch" aria-describedby="basic-addon2"/>
        <button type="submit" class="btn btn-primary mr-1" id="idSearchSp">Buscar</button>
      </div>
    </form>
{% endblock %}

{% block columns %}
    <thead>
        <tr class="align-middle table-success text-center table-bordered border-dark">
            <th scope="col" style="width: 25px;">Empleado</th>
            <th scope="col" style="width: 10%;">Opciones</th>
        </tr>
    </thead>
{% endblock %}

{% block rows %}
    {% for sue in sueldo %}
        <tbody>
            <tr class="align-middle table-warning text-center table-bordered border-dark">
                <td>{{ sue.empleado }}</td>
                <td class="acciones">
                    <a href="{% url 'ficha_Personal:registroSueldo' sue.empleado_id %}">🔎️ Ver información</a>
                </td>
            </tr>

        </tbody>
    {% endfor %}

{% endblock %}

aplicaciones/ficha_personal/templates/Sueldo/registroSueldo.html
{% extends 'boton_agr_reg.html' %}
{% load static %}

{% block controls %}
    <h4 class="fw-bold fst-italic text-secondary text-center">INFORMACION ACADEMICA</h4>
    <hr class="bg-success border-4 border-top border-success">
    <table class="table table-info table-striped table-bordered border-dark text-center">
    {% block columns %}
        <thead>
        <tr>
            <th scope="col" style="width: 5%;">#</th>
            <th scope="col" style="width: 10%;">Fecha</th>
            <th scope="col" style="width: 10%;">Sueldo</th>
            <th scope="col" style="width: 10%;">Estado</th>
            <th scope="col" style="width: 10%;">Opciones</th>
        </tr>
        </thead>
    {% endblock %}
    {% block rows %}
        {% for sue in sueldos %}
            <tbody>
                <tr class="align-middle table-info table-bordered border-dark text-center">
                    <td>{{ forloop.counter}}</td>
                    <td>{{ sue.fecha }}</td>
                    <td>{{ sue.sueldo }}</td>
                    <td>{% if sue.estado %}
                            ✅ Activo
                        {% else %}
                            🚫 Anulada
                        {% endif %}
                    <td class="acciones">
                        <a href="{% url 'ficha_Personal:actualizarSueldo' sue.id %}">✏️</a>
                        <a href="{% url 'ficha_Personal:deleteSueldo' sue.id %}">❌</a>
                    </td>
                </tr>
            </tbody>
        {% endfor %}
    {% endblock %}
        </table>

{% endblock %}